export * from './cart/cart.component';
export * from './contact/contact.component';
export * from './cognacdubois/cognacdubois.component';
export * from './disclaimer/disclaimer.component';
export * from './header/header.component';
export * from './medal/medal.component';
export * from './presentation/presentation.component';
export * from './products/products.component';
export * from './product/product.component';
